name: Pull Requests
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
      - uses: actions/setup-node@v4
      - run: npm cit
